# Generated by Django 4.0.3 on 2022-06-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='appreciation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ressources',
            name='descriptif',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ue',
            name='credit',
            field=models.IntegerField(null=True),
        ),
    ]
